### ISSUE TITLE
Question about Ldis in code

### ISSUE THREAD

**Issue by lao-ling-jie** [PRIS-CV/Mutual-Channel-Loss#14]
Wonderful work! But i have some question about Ldis. In your paper, i see specific channels belong to a class(eg. channel1 to channel3 is belong to class 1 ), but how to realize in code? you don't use targets when calculating the mask

**Comment by dingyf05** [comment]
Hi, this work enforces the feature channels to be class-aligned by conducting the GAP/CCMP/CWA operations instead of FC layers, thus only specific channels can contribute to the corresponding class in the cross-entropy loss. 
The mask in CWA drop channels of each class and does not distinguish the ground-truth label.
Hope this could help :smile:

**Comment by lao-ling-jie** [comment]
> Hi, this work enforces the feature channels to be class-aligned by conducting the GAP/CCMP/CWA operations instead of FC layers, thus only specific channels can contribute to the corresponding class in the cross-entropy loss.
> The mask in CWA drop channels of each class and does not distinguish the ground-truth label.
> Hope this could help 😄

Thanks for you kind reply! i konw what you said. in the paper, author assign channels belong to corresponding class (eg. 1-3 channels for class 1),but how to realize this idea in the code?

**Comment by dingyf05** [comment]
This idea can be simply realized with the GAP/CCMP/CWA operations (e.g., please refer to the implement line 232~239 in CUB-200-2011_ResNet18.py).  Specifically, the ith element g(F_i) of the output refers to the probability of the ith class, which only uses channels in the ith group.

**Comment by lao-ling-jie** [comment]
> This idea can be simply realized with the GAP/CCMP/CWA operations (e.g., please refer to the implement line 232~239 in CUB-200-2011_ResNet18.py). Specifically, the ith element g(F_i) of the output refers to the probability of the ith class, which only uses channels in the ith group.

I Get it! Thank you so much!
