### ISSUE TITLE
Can this idea transfer to the recognition task that has a lot of category?

### ISSUE THREAD

**Issue by lao-ling-jie** [PRIS-CV/Mutual-Channel-Loss#15]
Hi ! I have reproduced your paper and think it's a wonderful idea to make network learning diversity feature. I have a question that there is a small amont of categories in fined-grained recognition(eg. 200 classes), but how to deal with the task that has a big amount of categories(eg. 5000 classes)? And whether it work when i make a channel to represent more than one category？

**Comment by dongliangchang** [comment]
In the final version paper, we trying to use the  soft channel label  to make a channel to represent more than one category, you can refer that part.  But frankly speaking, the effect is not good. So, if you want to  deal with the task with  5000 classes,  maybe you need to set the channels equal to 5000*/xi.

**Comment by lao-ling-jie** [comment]
> In the final version paper, we trying to use the soft channel label to make a channel to represent more than one category, you can refer that part. But frankly speaking, the effect is not good. So, if you want to deal with the task with 5000 classes, maybe you need to set the channels equal to 5000*/xi.

Thanks for your reply！I will try it. Do you think it will affect the branch of feature diversity (L_div) if i  make a channel to represent more than one category?

**Comment by dongliangchang** [comment]
YES

**Comment by lao-ling-jie** [comment]
> YES

I Get it! Thank you very much!

**Comment by lao-ling-jie** [comment]
So can i say it's difficult to transfer your idea to the recognition task that has a lot of category?

**Comment by dongliangchang** [comment]
if you consider the parameters, YES. Otherwise, the answer is NO.
Maybe there need a more effective way to encoding the features.

**Comment by lao-ling-jie** [comment]
> if you consider the parameters, YES. Otherwise, the answer is NO.
> Maybe there need a more effective way to encoding the features.

Thanks
