### ISSUE TITLE
train

### ISSUE THREAD

**Issue by prretty** [PRIS-CV/Mutual-Channel-Loss#20]
when i train the model,there's a problem
![image](https://user-images.githubusercontent.com/50935736/116179088-48c12200-a749-11eb-9629-4f0a636f41ac.png)
please me again!

**Comment by dongliangchang** [comment]
epoch is here : https://github.com/PRIS-CV/Mutual-Channel-Loss/blob/4e2773595a0e0e95726a09f651d3c4e66dbd9945/CUB-200-2011_ResNet18.py#L405

**Comment by prretty** [comment]
Line 405 exists,but  it still doesn't show up"fixture 'epoch' not found".what make this?

**Comment by dongliangchang** [comment]
you need to check your code carefully.

**Comment by prretty** [comment]
ok , i will.thank you very much.
