### ISSUE TITLE
Is it possible to use MaxPool1D instead of MaxPool2D

### ISSUE THREAD

**Issue by captainst** [PRIS-CV/Mutual-Channel-Loss#22]
It's a very interesting paper and many thanks !

In the code, function **supervisor**, in order to perform the CCMP for Ldiv, you 
1. reshaped the branch from (batch, 512, 17*17) to (batch, 512, 17, 17)
2. used maxpool2d with kernel & stride (1, 3) to find max value on "channel" dimension
3. convert fro (batch, 512, 17, 17) back to (batch, 512, 17*17)

and the code is:

```
branch = branch.reshape(branch.size(0),branch.size(1), x.size(2), x.size(2))
branch = my_MaxPool2d(kernel_size=(1,cnum), stride=(1,cnum))(branch)  
branch = branch.reshape(branch.size(0),branch.size(1), branch.size(2) * branch.size(3))
```

I am wondering if it is possible to use MaxPool1D instead of MaxPool2D, to avoid those two reshape steps, like:
1. use maxpool1d directly on (batch, 512, 17*17), that is, 
    a. transpose(2,1)
    b. MaxPool1D (3)
    c. transpose(1,2)

In order to save some instructions during training :)

**Comment by dongliangchang** [comment]
I think this is right, many thanks.
