### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by pipnc** [PRIS-CV/Mutual-Channel-Loss#23]
作者您好，我在使用您的网络训练自己的模型的时候 因为数据集只有10个类，cnum还是保持为3不变吗？
我把通道数使用Conv2d调整为30了。目前效果不是很好。是要调整通道数还是要增大cnum？
是否还有其他参数需要调整？
    foo = [1] * 2 + [0] *  1
    bar = []
    for i in range(10):
        random.shuffle(foo)
        bar += foo
    bar = [bar for i in range(nb_batch)]
    bar = np.array(bar).astype("float32")
    bar = bar.reshape(nb_batch,10*channels,1,1)

**Comment by CHENSY-SIYU** [comment]
请问您是怎么解决的呢
