### ISSUE TITLE
About validation set

### ISSUE THREAD

**Issue by WindVChen** [PRIS-CV/Mutual-Channel-Loss#24]
Hi,

I recently did some research on fine-grained classification, and I found that you mentioned you didn't divide a validation set on CUB_200_2011 in your paper. Does it mean that when I do some experiments on CUB_200_2011, I can just take the test set as the valid set and I can take the best validation performance as my final result? 

Hope to get help from you, since I can't find descriptions about the validation set in other existing papers.
 
Thank you.

Kind regards.

**Comment by dongliangchang** [comment]
Yes
---------
Does it mean that when I do some experiments on CUB_200_2011, I can just take the test set as the valid set and I can take the best validation performance as my final result?

**Comment by WindVChen** [comment]
Thanks for your reply. I will close the issue.
