### ISSUE TITLE
Soft Channel labels

### ISSUE THREAD

**Issue by Gnabe** [PRIS-CV/Mutual-Channel-Loss#25]
Hi,

thanks for your very interesting work. I was wondering whether you could release your code for the soft channel labels.
Also, in https://github.com/PRIS-CV/Mutual-Channel-Loss/issues/15 you mentioned that it is not very good, even though the reported accuracy was increased. Could you explain the drawbacks of that method?

Greetings

**Comment by dongliangchang** [comment]
Sorry for being late. 
The MC-Loss will make the channels class-aligned, which will hurt the fine-tuning process. (Fine-tune needs slight variation in features, but MC-Loss will make the variation in features very large.)
Therefore, the current version of MC-Loss is not very suitable for fine-tuning. When we train the model from scratch, we can obtain huge improvements.
