### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by Gnabe** [PRIS-CV/Mutual-Channel-Loss#26]
Hello,

thanks again for your interesting work.
I however, struggle to reproduce your reported results on CUB200 with the Resnet50 backbone (87.3 %). 
If I understand https://github.com/Kurumi233/Mutual-Channel-Loss/issues/1 correctly, then you used entirely different hyperparameters than those mentioned in the paper?
I also saw that you deviated (as mentioned here:https://github.com/PRIS-CV/Mutual-Channel-Loss/issues/21) from the formulas of the paper, which impacts the hyperparameters. 
Could you point me to the correct combination of hyperparameters and code / formulas to reproduce your results?
I appreciate your help.

Greetings

**Comment by dongliangchang** [comment]
https://github.com/Kurumi233/Mutual-Channel-Loss/issues/1 has mentioned all hyperparameters.

**Comment by giangnguyen2412** [comment]
For those who could not reproduce the accuracy of RN18 untrained network on CUB, make sure that you use the image transforms and optimizer **the same as** provided by this repo.
