### ISSUE TITLE
what is the function of the "self.features_1 and self.features_2"?

### ISSUE THREAD

**Issue by Javacr** [PRIS-CV/Mutual-Channel-Loss#4]
https://github.com/PRIS-CV/Mutual-Channel-Loss/blob/1c1ff523f3d73c4f056a8a45621cb70fff89e725/CUB-200-2011.py#L187-L188

I see you split VGG16 into two parts, however, you don't use their features respectively, I don't know why you do that. Could you please make a explanation?

**Comment by dongliangchang** [comment]
Just for debugging purposes, you can ignore this.
