### ISSUE TITLE
About Channel-Wise Attention(CWA) in the code.

### ISSUE THREAD

**Issue by Hoodythree** [PRIS-CV/Mutual-Channel-Loss#5]
Great work!But I have little question about CWA.In the origianl paper, I see `M_i = diag(Mask_i)`, where `diag` is putting a vector on the princial diagonal of a diagonal matrix.But in the code below:
```
foo = [1] * 2 + [0] *  1
bar = []
for i in range(200):
    random.shuffle(foo)
    bar += foo
bar = [bar for i in range(nb_batch)]
```
I think `bar` is not a diagonal matrix.  Please point out my problem if I misunderstood the operation here.Thanks a lot.

**Comment by dongliangchang** [comment]
sorry for this confusion, the M_i just like [[0],[1],[0],[0],[1],[0]].T. 
CWA could be visualized as a random channel-dropping operation in each channel group.

**Comment by dongliangchang** [comment]
dot([0,1,0].t(), [1,2,3].t()) = [0,2,0].t()
matrix(diag([0,1,0].t()), [1,2,3].t()) = [0,2,0].t()
So, the code and the paper is consistent.
CWA could be visualized as a random channel-dropping operation in each channel group.

**Comment by dongliangchang** [comment]
![535949063158081301](https://user-images.githubusercontent.com/9455181/81775272-1bbb3580-951f-11ea-9906-2fd8743a7f70.jpg)

**Comment by Hoodythree** [comment]
Got it.Thanks for the response.

**Comment by AND2797** [comment]
```
foo = [1] * 2 + [0] *  1
bar = []
for i in range(200):
    random.shuffle(foo)
    bar += foo
bar = [bar for i in range(nb_batch)]
```
I had a small question about the code, here `foo = [1] * 2 + [0] *  1` is only good for 3 channels correct? If we want to increase the number of channels (say 5), then `foo = [1] * 3 + [0] * 2` is necessary, correct?

**Comment by dongliangchang** [comment]
Yes.  Please see Section III.A  The Discriminality Component  for details.
