### ISSUE TITLE
关于ξ的设置问题

### ISSUE THREAD

**Issue by Javacr** [PRIS-CV/Mutual-Channel-Loss#6]
作者你好，在论文中看到您使用VGG16的预训练模型时，为了去匹配最后一个卷积层的输出通道，将ξ设置成两种值。在train from scratch时，所有的通道中ξ设为统一值。
我想问的问题是：
1. 您有没有试图使用预训练模型去fine tune最后一个卷积层以及分类层，例如将卷积层使出通道设置为600，使得所有通道的ξ为3？效果如何呢？
2. 在您的代码中VGG的 _make_layers中 有这样一行代码：layers += [nn.AvgPool2d(kernel_size=1, stride=1)],核与步长都为1的平均池化，好像没有任何作用，这里的目的是什么呢？

**Comment by dongliangchang** [comment]
Q1. 您有没有试图使用预训练模型去fine tune最后一个卷积层以及分类层，例如将卷积层使出通道设置为600，使得所有通道的ξ为3？效果如何呢？
A1: 没有试过，但这是一个非常好的idea，值得尝试！欢迎开issue report你的结果，感谢！
Q2. 在您的代码中VGG的 _make_layers中 有这样一行代码：layers += [nn.AvgPool2d(kernel_size=1, stride=1)],核与步长都为1的平均池化，好像没有任何作用，这里的目的是什么呢？
A2: 你可以忽略这一行code。VGG16的代码我参考了这个repo ：[Train CIFAR10 with PyTorch](https://github.com/kuangliu/pytorch-cifar)
