### ISSUE TITLE
关于Feature channels和FC的疑惑．

### ISSUE THREAD

**Issue by Javacr** [PRIS-CV/Mutual-Channel-Loss#7]
作者你好，最近用您的网络在鸟类和汽车数据集进行了训练．在无预训练模型的条件下，分别达到了67.33(论文65.98)和90.34(论文90.85)的准确率．验证了模型的有效性．但是我今天在看模型结构的时候，有些疑惑．
Feature channels中Ｎ = ξ * C,按照论文中的描述，通过索引，某组中ξ个特征图用于表示某类的特征．但是当Feature channels通过全连接层时，通道已被打乱融合了，这时再进行分类，组的概念就已经消失了，便不具有特征图与类别的针对性了．所以想请问我的理解错误在哪儿？

**Comment by dongliangchang** [comment]
增加噪声，提高模型的泛化能力。你可以试试只输入特定组channel的效果，欢迎report你的结果，谢谢。
