### ISSUE TITLE
Interfacing with GradCAM?

### ISSUE THREAD

**Issue by AND2797** [PRIS-CV/Mutual-Channel-Loss#9]
Is it possible to update the documentation or provide some instructions on how we can reproduce GradCAM like visualizations with the code that is provided?

**Comment by dongliangchang** [comment]
You can find the related code at [pytorch-cnn-visualizations](https://github.com/utkuozbulak/pytorch-cnn-visualizations) Due to a group channels is belonging to a certain class in our method , we can directly visualize the channels without Gradient-weighted. (e.g., as the 1-3 channels belonging to the first class, we can directly visualize those channels without Gradient-weighted). Just revise the related  code for you need.

**Comment by AND2797** [comment]
So the activation maps from MCLoss are essentially the same as what we get from GradCAM?

**Comment by dongliangchang** [comment]
No, there has a typo. We don't use vanilla GradCAM to visualize the channels (fig 5 & 7), we directly visualuze the channels beonging to a certain class. Sorry for this.

**Comment by dongliangchang** [comment]
E.g., for the first class, we known that the first channel group (1-3 channels) belonging to it. So, we don't need to use the grad to weighted all channels (GradCAM).

**Comment by AND2797** [comment]
Sorry, I am a little confused so just to confirm I will summarize what I have understood and please correct me if it is wrong. The MCLoss code gives us a feature map of all class activations. For eg: there are 50 classes and 3 channels, the feature map will total have 150 activation maps, and if we know that the correct class is class 1, then channels 1 - 3 will tell us what are the discriminant parts for that class. So the MCLoss code already gives us these activation maps and we can directly use this to visualize the channels and gradCAM Is not required. 

If this is the case then do we super-impose the activation maps on the input image by upsampling the activation maps to 224 x 224?

**Comment by dongliangchang** [comment]
There is no problem with your understanding for visualization.

Yes, just revise the code of  gradCAM, remove the channel weighted, and then chose one channel to visualizaiton.
Here is a example:
for GradCAM: 
heatmap =  a_1 * channel_1 + a_2 * channel_2+ ... + a_n * channel_n.
for us (the first class, and /xi=3):
heatmap_0 = channels[0]
heatmap_1 = channels[1]
heatmap_2 = channels[2]
some details are omitted here

**Comment by AND2797** [comment]
I was curious if you tried guided gradcam along with gradcam in your experiments?

**Comment by dongliangchang** [comment]
No. the  attention map attained by the guided gradcam, maybe can used to guidance the MC-Loss.

**Comment by AND2797** [comment]
Thank you
